"""create ticket and ticket_action tables

Revision ID: 4a24ed7a646c
Revises: 
Create Date: 2026-03-18 12:39:59.191014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a24ed7a646c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Enum definition
ticketstatusenum = sa.Enum(
    "open", "running", "failed", "success", "needs_review",
    name="ticketstatusenum"
)

def upgrade():
    # ### commands auto generated by Alembic ###
    ticketstatusenum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'ticket',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('type', sa.String(length=100), nullable=False),
        sa.Column('status', ticketstatusenum, nullable=False, server_default='open'),
    )

    op.create_table(
        'ticket_action',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('ticket_id', sa.Integer(), sa.ForeignKey('ticket.id', ondelete='CASCADE'), nullable=False),
        sa.Column('action', sa.String(length=255), nullable=False),
        sa.Column('success', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table('ticket_action')
    op.drop_table('ticket')
    ticketstatusenum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
